services:
  postgres:
    image: postgres:18
    container_name: resume-analyzer-postgres
    environment:
      POSTGRES_DB: resume_analyzer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - resume_analyzer_pgdata:/var/lib/postgresql

volumes:
  resume_analyzer_pgdata: